### PR TITLE
allow spells to active global modifier on caster sheet

### PR DESCRIPTION
**Pull request by Stexinator**
closes https://github.com/Stexinator/TheWitcherTRPG/issues/114 https://github.com/Stexinator/TheWitcherTRPG/issues/131

### CODE REVIEW

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at I found a bug where the armor of locations are not calculated when applying damage. So releasing this fast would be nice

**Comment by AlexanderTheGr3at** [comment]
> @pedroaugustobt @moliloo @AlexanderTheGr3at I found a bug where the armor of locations are not calculated when applying damage. So releasing this fast would be nice

Sorry I've been mia. Got bad medical news. I'll test today.

**Comment by pedroaugustobt** [comment]
- Allow spells to active global modifier on caster sheet - OK

- refactor scripts + fix location armor not applied - OK

- get globalModifier from compendium when not on actor - OK

- add critical wounds to context menu - Some errors:

In applyCrit.js there is an error on line 42 and 50. The error causes the damage to not be applied correctly, basically there is a missing point in derivedStats.hp -> "actor.system.derivedStatshp.value".
image

**Comment by Stexinator** [comment]
Fixed

**Comment by pedroaugustobt** [comment]
@Stexinator It's working!

**Comment by Stexinator** [comment]
https://github.com/Stexinator/TheWitcherTRPG/issues/131 also fixed

**Pull request merged**
