### PR TITLE
fix diagrams not accepting associated items

### PR DESCRIPTION
**Pull request by Stexinator**
closes https://github.com/Stexinator/TheWitcherTRPG/issues/117 https://github.com/Stexinator/TheWitcherTRPG/issues/124 https://github.com/Stexinator/TheWitcherTRPG/issues/115

### CODE REVIEW

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at I found a game breaking regression so I want to release it today. Would be nice if you could do some tests

**Comment by moliloo** [comment]
I will test today, sorry for desapegar and dont make teste last week, i was really busy with college and home moving

**Comment by Stexinator** [comment]
> I will test today, sorry for desapegar and dont make teste last week, i was really busy with college and home moving

No worries, every testing is helpful and with 3 testers there is mostly someone that got time :)
Also I test all of the stuff when developing the features. But sometimes things slip or my data is already more advanced then the real user data out there :)

**Comment by AlexanderTheGr3at** [comment]
> @pedroaugustobt @moliloo @AlexanderTheGr3at I found a game breaking regression so I want to release it today. Would be nice if you could do some tests



> @pedroaugustobt @moliloo @AlexanderTheGr3at I found a game breaking regression so I want to release it today. Would be nice if you could do some tests



> @pedroaugustobt @moliloo @AlexanderTheGr3at I found a game breaking regression so I want to release it today. Would be nice if you could do some tests



> @pedroaugustobt @moliloo @AlexanderTheGr3at I found a game breaking regression so I want to release it today. Would be nice if you could do some tests

Everything seems to be working well for me. Only errors I'm getting are depreciation errors.


[localhost-1717608324438.log](https://github.com/user-attachments/files/15594351/localhost-1717608324438.log)
[localhost-1717608715458.log](https://github.com/user-attachments/files/15594363/localhost-1717608715458.log)

**Comment by AlexanderTheGr3at** [comment]
Checked the new spell push. I just did a basic test with the default Mage and everything seems to be in order for spells.

SpellTest

**Pull request merged**
