### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Stexinator**

### CODE REVIEW

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release.

**Comment by AlexanderTheGr3at** [comment]
@Stexinator 

The first thing I notice when I open is some spells are missing due to percentage errors.

Missing

I also can't get any items to actually store in a container so I can't check "fix container not showing weight of stored items" unless I'm misinterpreting what that is suppose to mean.

**Comment by pedroaugustobt** [comment]
I didn't have this error, maybe because I use all the spells in the compendium.

> @Stexinator
> 
> The first thing I notice when I open is some spells are missing due to percentage errors.
> 
> Missing
> 
> I also can't get any items to actually store in a container so I can't check "fix container not showing weight of stored items" unless I'm misinterpreting what that is suppose to mean.

**Comment by pedroaugustobt** [comment]
@Stexinator , I did all the tests regarding signals, global modifiers and containers, everything is working. Probably in friday, I will send the pr's from styles and layout for you to merge

**Comment by AlexanderTheGr3at** [comment]
> I didn't have this error, maybe because I use all the spells in the compendium.
> 
> > @Stexinator
> > The first thing I notice when I open is some spells are missing due to percentage errors.
> > Missing
> > I also can't get any items to actually store in a container so I can't check "fix container not showing weight of stored items" unless I'm misinterpreting what that is suppose to mean.

Yeah, I'm not sure what was up but upon restarting it worked correctly. I've tested everything else except the container stuff and it seems to be working. The container weight I still don't quite understand what it's supposed to be tracking. Is it just the new boxes at the bottom I can enter weight into? Or am I supposed to be able to actually store things in the container (like a sublist of things inside)?

**Comment by pedroaugustobt** [comment]
image
You can (drag an item by name) store it inside the container

**Comment by Stexinator** [comment]
> > I didn't have this error, maybe because I use all the spells in the compendium.
> > > @Stexinator
> > > The first thing I notice when I open is some spells are missing due to percentage errors.
> > > Missing
> > > I also can't get any items to actually store in a container so I can't check "fix container not showing weight of stored items" unless I'm misinterpreting what that is suppose to mean.
> 
> Yeah, I'm not sure what was up but upon restarting it worked correctly. I've tested everything else except the container stuff and it seems to be working. The container weight I still don't quite understand what it's supposed to be tracking. Is it just the new boxes at the bottom I can enter weight into? Or am I supposed to be able to actually store things in the container (like a sublist of things inside)?

You might have the old containers that you cannot create anymore. If you use the dedicated container item instead of a valuables container you will see the functionalities

**Comment by WitcherFromPoznan** [comment]
It's works for me.

**Comment by AlexanderTheGr3at** [comment]
> > > I didn't have this error, maybe because I use all the spells in the compendium.
> > > > @Stexinator
> > > > The first thing I notice when I open is some spells are missing due to percentage errors.
> > > > Missing
> > > > I also can't get any items to actually store in a container so I can't check "fix container not showing weight of stored items" unless I'm misinterpreting what that is suppose to mean.
> > 
> > 
> > Yeah, I'm not sure what was up but upon restarting it worked correctly. I've tested everything else except the container stuff and it seems to be working. The container weight I still don't quite understand what it's supposed to be tracking. Is it just the new boxes at the bottom I can enter weight into? Or am I supposed to be able to actually store things in the container (like a sublist of things inside)?
> 
> You might have the old containers that you cannot create anymore. If you use the dedicated container item instead of a valuables container you will see the functionalities

Yeah I figured it out. There are two container categories now, even when I delete and reimport the compendium. The grey folder works, the black doesn't.

Untitled

**Pull request merged**
