### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Stexinator**
closes https://github.com/Stexinator/TheWitcherTRPG/issues/126

### CODE REVIEW

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for testing

**Comment by AlexanderTheGr3at** [comment]
> @pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for testing

I'll test out tonight!!

**Comment by pedroaugustobt** [comment]
PTBR Translation - Ok
Fix elderfolk diagram sorting - Ok
Create chat and dialog template folders and move corresponding templates - Ok
Rework critical wounds data handling - Ok
Rename attack locations - OK
Crit wounds apply their modifier to stats, derived stats and skills - Some errors happen:
Cracked Ribs
- Does not reduce Encumbrance in Treated
- Did not decrease by -1 BODY in Stabilized

Torn Stomach
- When Torn Stomach's crit is active, I cannot roll any Skills

Compound Leg Fracture, Dismembered Leg
- The same error occurs as Torn Stomach

I think the divisions are not applied correctly in Skills, as in Stats it works normally

**Comment by AlexanderTheGr3at** [comment]
- [x] Elderfolk diagram sorting 
- [x] Create chat and dialog template folders and move corresponding templates (Think I checked this one right)
- [ ] Rework critical wounds data handling
- [x] Rename attack locations
- [ ] Crit wounds apply their modifier to stats, derived stats and skills

- Cracked Jaw "None" Verbal Combat "Ignore" doesn't apply -2 (May be intentional, rules don't specially specify this skill is affected)
- Cracked Jaw "None" Verbal Combat "Disengage" doesn't apply -2 (May be intentional, rules don't specially specify this skill is affected)
- Cracked Jaw "None" Verbal Combat "Study" doesn't apply -2 (May be intentional, rules don't specially specify this skill is affected)
- Cracked Jaw "None" Verbal Combat "Bride" doesn't apply -2 (May be intentional, rules don't specially specify this skill is affected)
- Cracked Jaw "Stabilized" Verbal Combat "Ignore" doesn't apply -2 (May be intentional, rules don't specially specify this skill is affected)

- Cracked Ribs stabilized condition does not update body appropriately. 
- Cracked Ribs treated does not reduce encumbrance

I get this error:
[localhost-1717730209703.log](https://github.com/user-attachments/files/15699071/localhost-1717730209703.log)

Unrelated Errors:

Verbal Combat Counter Argument rolls with two +0 (N/A). No error in log. Screenshot attached.
 
Verbal



I'll update more tomorrow as I dive into it more.

**Comment by Stexinator** [comment]
This is ready for another round of testing

**Comment by pedroaugustobt** [comment]
@Stexinator It's working fine!

**Pull request merged**
