### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Stexinator**

### CODE REVIEW

**Comment by Stexinator** [comment]
closes https://github.com/Stexinator/TheWitcherTRPG/issues/83 https://github.com/Stexinator/TheWitcherTRPG/issues/92 https://github.com/Stexinator/TheWitcherTRPG/issues/94

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo the dev branch is now complete for the next version. I intend to release it coming sunday

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo I would release in ~1 hour. Did you find anything that should be fixed in this release?

**Comment by moliloo** [comment]
No, i don't find any issues to be fixed for now

**Comment by AlexanderTheGr3at** [comment]
> @pedroaugustobt @moliloo I would release in ~1 hour. Did you find anything that should be fixed in this release?

Looking forward to the release!

**Pull request merged**
