### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Stexinator**

### CODE REVIEW

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release.

Due to the support for modules everything that rolls dice needs to be tested. Sorry :(

With this amount of testing I want to wait till two people have given their okay.

**Comment by pedroaugustobt** [comment]
> @pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release.
> 
> Due to the support for modules everything that rolls dice needs to be tested. Sorry :(
> 
> With this amount of testing I want to wait till two people have given their okay.

Okay, as soon as I have some time, I'll take it out and test it with all the changes.

**Comment by pedroaugustobt** [comment]
@Stexinator I'm creating some macros to use with Condition Lab & Triggler, do you still need help to continue Wiki?

**Comment by AlexanderTheGr3at** [comment]
> @pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release.
> 
> Due to the support for modules everything that rolls dice needs to be tested. Sorry :(
> 
> With this amount of testing I want to wait till two people have given their okay.

What modules is it supporting? Wanna make sure I have them all for testing.

**Comment by Stexinator** [comment]
> @Stexinator I'm creating some macros to use with Condition Lab & Triggler, do you still need help to continue Wiki?

Sure thing. Can you create an issue where you add what you want to see in the wiki?

**Comment by Stexinator** [comment]
> > @pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release.
> > Due to the support for modules everything that rolls dice needs to be tested. Sorry :(
> > With this amount of testing I want to wait till two people have given their okay.
> 
> What modules is it supporting? Wanna make sure I have them all for testing.

All the ones the community will write :P Currently there is nothing I am aware off.

**Comment by pedroaugustobt** [comment]
- [x] Fixed Enhancement Diagrams not appearing on the sheet
- [x] Fix texts not translated in attack dialog
- [x] fix academicKnowledge resetting
- [x] Fix duplication effect throwable items
- [x] fix deprecations in alchemical-sheet
- [x] fix deprecations in armor-sheet

I didn't understand what to test with this modification -> add support for modules changing config stuff - eff3d6a

**Comment by Stexinator** [comment]
@pedroaugustobt for 
> I didn't understand what to test with this modification -> add support for modules changing config stuff - [eff3d6a](https://github.com/Stexinator/TheWitcherTRPG/commit/eff3d6a6e182a9dcd171b1310aa2f07823cf72dd)

you just need to test that everything works as before

**Comment by Stexinator** [comment]
You could also test everything in https://github.com/Stexinator/TheWitcherTRPG/wiki/Module-Support but that is not necessary

**Comment by pedroaugustobt** [comment]
At first everything is working

**Comment by AlexanderTheGr3at** [comment]
**Combat:**

- [x] Initiative Roll
- [x] Saving Throw
- [x] Crit/Fumble

Attack Rolls:

- [x] Normal Strike
- [x] Fast Strike
- [x] Strong Strike
- [x] Joint Strike 

Defense Rolls:

- [x] Dodge
- [x] Reposition
- [x] Block
- [x] Parry
- [x] Parry Thrown Weapon
- [x] Magic Resist

Verbal Combat

- [x] Seduce
- [x] Persuade
- [x] Appeal
- [x] Befriend
- [x] Deceive
- [x] Ridicule
- [x] Intimidate
- [x] Ignore
- [x] Counterargue (Should be a space or - between these two words)
- [x] Change Subject (No description of what the skill does in the roll window)
- [x] Disengage
- [x] Romance
- [x] Study
- [x] Imply with Persuasion - ( with needs to be made a capital)
- [x] Imply With Deceit
- [x]  Bribe 
______________________________________________________________________________________

**Skill Rolls:**

- [x] Intelligence Skills
- [x] Reflex Skills
- [x] Willpower Skills
- [x] Dexterity Skills
- [x] Crafting Skills
- [x] Body Skills
- [x] Empathy Skills 

___

**Crafting Rolls:**

- [x] Witcher Decotions (Rolls work but items are only added/removed if real craft is checked off, not sure if intended)
- [x] Witcher Potions (Rolls work but items are only added/removed if real craft is checked off, not sure if intended)
- [x] Oils (Rolls work but items are only added/removed if real craft is checked off, not sure if intended)

___

**Magic Rolls: (Tested a few of each type)**
- [x] Spells
- [x] Invocations
- [x] Signs

___

**Global Modifiers:**
- [x] Skills
- [x] Statistics
- [x] Derived
- [x] Special Effects

All apply and roll correctly.

___

**Loot Roll Tables:**
- [x] Mundane Items
- [x] Occult Items
- [x] Strange Items
- [x] Self Made Loot Table
- [x] Enemy Loot 

___

**Character Creation Rolls**
- [x] Profession Tables
- [x] Family & Parents Tables
- [x] Family Fate Tables
- [x] Most Influential Friends Tables
- [x] Nilfgaard Vassal Origin
- [x] Origins Tables
- [x] Parental Fate Tables
- [x] Parents Tables
- [x] Siblings Tables
- [x] Which Parent 

___

**Life Events Table:**

- [x] Allies Tables
- [x] Enemies Tables
- [x] Fortune
- [x] Fortune or Misfortune
- [x] Misfortune
- [x] Romance
- [x] Romance: Problematic Love
- [x] Romance: Romantic Tragedy

___

**Style and Values Tables:
-[x] Affectations
-[x] Clothing
-[x] Hair Style
-[x] Personality
-[x] Feelings on People
-[x] Ideals
-[x] Valued Person

___

I think I rolled everything I could find and it all seems to be in working order. If I missed anything let me know.

**Pull request merged**
