### PR TITLE
add context menu for items

### PR DESCRIPTION
**Pull request by Stexinator**

### CODE REVIEW

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at I would like to merge it today or tomorrow

**Comment by Stexinator** [comment]
I completly overhauled ``apply damage`` in preparation of ``damage to all locations``. Due to the rewrite being about 90% of the code with several fixes of unknown bugs I suggest to give this area extra attention

**Comment by AlexanderTheGr3at** [comment]
> I completly overhauled `apply damage` in preparation of `damage to all locations`. Due to the rewrite being about 90% of the code with several fixes of unknown bugs I suggest to give this area extra attention

I'm getting some issues trying to apply damage to Player Characters

DamageError


[localhost-1720784493332.log](https://github.com/user-attachments/files/16193346/localhost-1720784493332.log)
[localhost-1720784481437.log](https://github.com/user-attachments/files/16193347/localhost-1720784481437.log)

**Comment by AlexanderTheGr3at** [comment]
- [x] Configuration sheets for weapon and spells (Functioning ones)

- [ ] **Alchemical configuration sheet:** The sheet does appear, and the using the check boxes does add the attended effect, not sure how to add "Global Modifers" to an item as all it gives is a bar to write a name. I would suggest making items that are supposed to be consumable set to that by default. I would also suggest adding a box for "Is throwable" for things like bombs and "Zerrikanian Fire". I also noticed that if you drag an item to a sheet before applying "Is consumable", then apply "Is consumable" to the orignal item in the Alchemical section it does not update the items added to the sheet to be consumable.

- [x] Fixed wrong line reminder for armor piercing.

- [ ] **Added ability to consume items and apply effects:** We've got some issues with this one. For one, like above I believe items that are supposed to be consumable be set that to default (Some alchemical items, potions, ect). Secondly, items like "White Raffard's Decoction" is suppose to heal 1hp per round, but as it is I can only get it to heal 1hp total. Inside and outside of combat. I don't know if this is because a die never rolls for it. I do get this message in the log. [localhost-1720785684347.log](https://github.com/user-attachments/files/16193740/localhost-1720785684347.log). Toxicity also doesn't seem to be applied by any items.

- [x] Fixed failed crafting writing undefined instead of item name.

**Comment by Stexinator** [comment]
> Alchemical configuration sheet: The sheet does appear, and the using the check boxes does add the attended effect, not sure how to add "Global Modifers" to an item as all it gives is a bar to write a name. I would suggest making items that are supposed to be consumable set to that by default. 

The compendium will eventually be updated. The system itself holds no knowledge what item exists, so there is no default for things you think are consumable

> I would also suggest adding a box for "Is throwable" for things like bombs and "Zerrikanian Fire".

Throwables are handled via weapons

>  I also noticed that if you drag an item to a sheet before applying "Is consumable", then apply "Is consumable" to the orignal item in the Alchemical section it does not update the items added to the sheet to be consumable.

This is common foundry behaviour. A copy of the dropped item is created in the sheet. They are de-coupled so no synchronisation is handeled. On the other side the whole stack of items will be modified if you modify it in the sheet.

> Secondly, items like "White Raffard's Decoction" is suppose to heal 1hp per round, but as it is I can only get it to heal 1hp total.

The system has no concept of rounds. To build something like this is a larger endeavor. You can add your use-cases to https://github.com/Stexinator/TheWitcherTRPG/issues/161

The error is from illegal syntax. You can only input numbers or XdY.

**Comment by AlexanderTheGr3at** [comment]
Thanks for the detailed write up. Helps me better understand how the system works for testing.

**Comment by Stexinator** [comment]
> I'm getting some issues trying to apply damage to Player Characters

Fixed

**Comment by AlexanderTheGr3at** [comment]
- [x] Configuration sheets for weapon and spells (Functioning ones)

- [x] Alchemical configuration sheet, need compendium update for defaults, otherwise all is good. @Siryphas

- [x] Fixed wrong line reminder for armor piercing.

- [x] Added ability to consume items and apply effects: Item's should be updated in compendium to have their default values and properties set to make it easier on new users. @Siryphas

- [x] Fixed failed crafting writing undefined instead of item name. 


Other than my two comments on the compendium all looks like it is working to me.

**Pull request merged**
