### PR TITLE
remove v11 compatible deprecations

### PR DESCRIPTION
**Pull request by Stexinator**
This gets rid of some deprecations that can also be handled in v11

I think in 1 or 2 releases I will drop v11 support.

### CODE REVIEW

**Comment by Stexinator** [comment]
This can be tested whenever. I dont know if I will put user features into this release

**Comment by Stexinator** [comment]
closes https://github.com/Stexinator/TheWitcherTRPG/issues/99

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo any news yet?

**Comment by AlexanderTheGr3at** [comment]
> @pedroaugustobt @moliloo any news yet?

How can I help with this stuff?

**Comment by Stexinator** [comment]
@AlexanderTheGr3at I made a little list. You can copy it and check all of it. Additionally look into the linked stories and check if the things work

**Comment by AlexanderTheGr3at** [comment]
> @AlexanderTheGr3at I made a little list. You can copy it and check all of it. Additionally look into the linked stories and check if the things work

Is there somewhere we can message like discord or something? I want to help, but want to make sure I'm doing it all right.

**Comment by Stexinator** [comment]
My discord is linked in the system

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at  target is sunday again

**Comment by AlexanderTheGr3at** [comment]
> @pedroaugustobt @moliloo @AlexanderTheGr3at target is sunday again

I'll check it out today.

**Comment by AlexanderTheGr3at** [comment]
* [ ✓]  Weapon attack skill handling changed -> currently selected skill is broken

* [ ✓]  everything chat card context menu

* [✓ ]  everything active effect
 
 * [✓ ]  spells and attack now respect modifiers and active effects on skills
 
 * [ ✓]  active effects can no longer be created

  * [✓ ]  global modifiers replace them

I tested and other than having to reset some weapon skills before use all seem to be working as intended.

**Comment by Stexinator** [comment]
I had to change a major point of global modifiers. Can you test them again? Thanks

**Comment by AlexanderTheGr3at** [comment]
@Stexinator I get a large amount of errors in the log when opening the world now. It also seems now the character sheet no longer works. It won't save any of the changes I make. 
[localhost-1717356129414.log](https://github.com/user-attachments/files/15526584/localhost-1717356129414.log)
[localhost-1717356126775.log](https://github.com/user-attachments/files/15526585/localhost-1717356126775.log)
[localhost-1717356185068.log](https://github.com/user-attachments/files/15526586/localhost-1717356185068.log)
[localhost-1717356181902.log](https://github.com/user-attachments/files/15526587/localhost-1717356181902.log)
[localhost-1717356179395.log](https://github.com/user-attachments/files/15526588/localhost-1717356179395.log)
[localhost-1717356176780.log](https://github.com/user-attachments/files/15526589/localhost-1717356176780.log)
[localhost-1717356174625.log](https://github.com/user-attachments/files/15526590/localhost-1717356174625.log)
[localhost-1717356169670.log](https://github.com/user-attachments/files/15526591/localhost-1717356169670.log)
[localhost-1717356166297.log](https://github.com/user-attachments/files/15526592/localhost-1717356166297.log)
[localhost-1717356163366.log](https://github.com/user-attachments/files/15526593/localhost-1717356163366.log)
[localhost-1717356160229.log](https://github.com/user-attachments/files/15526594/localhost-1717356160229.log)
[localhost-1717356157007.log](https://github.com/user-attachments/files/15526595/localhost-1717356157007.log)
[localhost-1717356154069.log](https://github.com/user-attachments/files/15526596/localhost-1717356154069.log)
[localhost-1717356150681.log](https://github.com/user-attachments/files/15526597/localhost-1717356150681.log)
[localhost-1717356148330.log](https://github.com/user-attachments/files/15526598/localhost-1717356148330.log)
[localhost-1717356144812.log](https://github.com/user-attachments/files/15526599/localhost-1717356144812.log)
[localhost-1717356142273.log](https://github.com/user-attachments/files/15526600/localhost-1717356142273.log)
[localhost-1717356139950.log](https://github.com/user-attachments/files/15526601/localhost-1717356139950.log)
[localhost-1717356135477.log](https://github.com/user-attachments/files/15526602/localhost-1717356135477.log)
[localhost-1717356131701.log](https://github.com/user-attachments/files/15526603/localhost-1717356131701.log)

https://github.com/Stexinator/TheWitcherTRPG/assets/59134326/f2c5ffa1-58c8-4e80-9aa5-fee9f6ea8e7f

**Comment by AlexanderTheGr3at** [comment]
@Stexinator 

Alright tested again. It seems my one character is just messed up. Can't do anything with their sheet. I tried on another character and the Global Mods seem
 to apply, but when they are you can't roll any attacks. I've attached the logs and uploaded a [video](https://youtu.be/xhusIdQ0tHE). I've also attached the export for the one character that's messed up now. 

[localhost-1717358212623.log](https://github.com/user-attachments/files/15526685/localhost-1717358212623.log)
[localhost-1717358161616.log](https://github.com/user-attachments/files/15526686/localhost-1717358161616.log)
[localhost-1717358239531.log](https://github.com/user-attachments/files/15526687/localhost-1717358239531.log)
[fvtt-Actor-artemas-jqDRHdGk6VyBGB1W.json](https://github.com/user-attachments/files/15526703/fvtt-Actor-artemas-jqDRHdGk6VyBGB1W.json)

**Comment by Stexinator** [comment]
Can you upload the character which cannot roll attacks? I think there is something wrong with applied status effects. They need to be a number now but there is going something wrong.

Artemas had some broken values. I added safeguards to convert them back to a valid format. The culprit was the int: 0

**Comment by AlexanderTheGr3at** [comment]
Here are two character export examples of the attacks not working after applying global modifiers

[fvtt-Actor-ivan-h9pbABJ5bdYQfmGc.json](https://github.com/user-attachments/files/15531277/fvtt-Actor-ivan-h9pbABJ5bdYQfmGc.json)
[fvtt-Actor-sir-engelnam-of-birchroot-RQNb3oZkC0qq8XKb.json](https://github.com/user-attachments/files/15531278/fvtt-Actor-sir-engelnam-of-birchroot-RQNb3oZkC0qq8XKb.json)

**Comment by Stexinator** [comment]
> @Stexinator I've also found an issue with enemy attacks. None of them seem to roll right now. I don't know if this is because of the same thing with PC attacks needing to manually change the skill or not. That doesn't seem to be an option for enemies though. [localhost-1717405156458.log](https://github.com/user-attachments/files/15531401/localhost-1717405156458.log) [localhost-1717405146944.log](https://github.com/user-attachments/files/15531402/localhost-1717405146944.log)

It is the same as for PC, all weapon skills for PC and NPC need to be reset

**Comment by pedroaugustobt** [comment]
Hey, I'm testing everything within Foundry, and I came across some errors, here's a list of what happened:

- Items are not placed in diagrams, I drag the item to the diagram and do not see any error notification in the console.

- When I roll Defense (dodge, reposition, etc.), the value in the skill always has a 0 in front of the value, for example, if my Dodge skill is 3, the system calculates 1d10 + 6 (REF) + 30 (Dodge)

Until then, the global and normal effects are working, I'm still going to be testing more this week with some friends of mine and checking that there are no serious errors.

**Comment by Stexinator** [comment]
grafik
Are you on the newest version? One or two versions ago the displayed formula had an extra 0 but that is fixed already

**Comment by Stexinator** [comment]
Diagrams will be fixed in the next update, there is currently no workaround

**Comment by pedroaugustobt** [comment]
> grafik Are you on the newest version? One or two versions ago the displayed formula had an extra 0 but that is fixed already

It only works when the Display roll's details setting is checked, if it is not checked, this bug happens

**Comment by Stexinator** [comment]
Fixed in next update

**Comment by pedroaugustobt** [comment]
@Stexinator 
Would you prefer that I create issues with the errors I find, or can it be done here?

**Comment by Stexinator** [comment]
create issues, this PR is closed, so this is not the right place for it

**Pull request merged**
