### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Stexinator**

### CODE REVIEW

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release.

Here the weapon skills were added to module support so this might need some extra attention.
The fix for automated animations can only be tested in concert with the changes to the module https://github.com/otigon/automated-jb2a-animations/pull/702

**Comment by pedroaugustobt** [comment]
> @pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release.
> 
> Here the weapon skills were added to module support so this might need some extra attention. The fix for automated animations can only be tested in concert with the changes to the module [otigon/automated-jb2a-animations#702](https://github.com/otigon/automated-jb2a-animations/pull/702)

It’s all working.

**Comment by Stexinator** [comment]
Does anyone else want to do some testing?

**Comment by moliloo** [comment]
I will test today

**Comment by moliloo** [comment]
@Stexinator i have a error here, but i don't know if its me make some mistake, i am not that good to deal with modules, i downloaded your fork of the module and add manually to foundry, but this error appears and the module aren't show in Add-on Modules, if you can help me how to solve this i can make the tests 
```
Invalid module "autoanimations" detected in directory "automated-jb2a-animations-fix-fix_witchertrpg_integration"
```

**Comment by Stexinator** [comment]
@moliloo you have to hit it until it looks like the original. The module was renamed at least once so you have to make sure that the folder name is identical to the id in the module.json

**Comment by WitcherFromPoznan** [comment]
> > @pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release.
> > Here the weapon skills were added to module support so this might need some extra attention. The fix for automated animations can only be tested in concert with the changes to the module [otigon/automated-jb2a-animations#702](https://github.com/otigon/automated-jb2a-animations/pull/702)
> 
> It’s all working.

I'm sorry for interrupting the conversation, but how did you manage to make an automatic animation work? I've been working on it for about 3 hours and it still doesn't work.

**Comment by pedroaugustobt** [comment]
> > > @pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release.
> > > Here the weapon skills were added to module support so this might need some extra attention. The fix for automated animations can only be tested in concert with the changes to the module [otigon/automated-jb2a-animations#702](https://github.com/otigon/automated-jb2a-animations/pull/702)
> > 
> > 
> > It’s all working.
> 
> I'm sorry for interrupting the conversation, but how did you manage to make an automatic animation work? I've been working on it for about 3 hours and it still doesn't work.

Are you using this repository as a system in Foundry?

**Comment by WitcherFromPoznan** [comment]
> > > > @pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release.
> > > > Here the weapon skills were added to module support so this might need some extra attention. The fix for automated animations can only be tested in concert with the changes to the module [otigon/automated-jb2a-animations#702](https://github.com/otigon/automated-jb2a-animations/pull/702)
> > > 
> > > 
> > > It’s all working.
> > 
> > 
> > I'm sorry for interrupting the conversation, but how did you manage to make an automatic animation work? I've been working on it for about 3 hours and it still doesn't work.
> 
> Are you using this repository as a system in Foundry?

Sorry don't know what is "repository" but if it means that i am using system from  Stexinator then yes.

**Comment by pedroaugustobt** [comment]
Yeah, what version is it?

**Comment by WitcherFromPoznan** [comment]
Current

**Comment by WitcherFromPoznan** [comment]
Being more precise 1.042. There is no error. Global Automatic Recognition finds swords, bites and claws but still doesn't work. I even made custom Item in Menu but they also didn't work.

**Comment by pedroaugustobt** [comment]
My discord ```Pedro Augusto#6313```

**Pull request merged**
